baseURL = "https://chicco182.github.com/stefanovalentini/"
languageCode = "en"
title = "Stefano Valentini's site"
theme = "coder"
defaultcontentlanguage = "it" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "chicco182" # Enable or disable Disqus.

[params] # theme parameters
    author = "Stefano Valentini" # Author's name.
    info = "WEB ENGINEER" # Author's job title or info.
    description = "Stefano Valentini's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "avatar_stefano2.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "© Stefano Valentini" # Add footer content
    #fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    #fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/chicco182/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/stefanovalentini82/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/Valentini1982/"
[[params.social]]
    name = "Instagram"
    weight = 2
    url = "https://www.instagram.com/stefanovalentini82/"


# Menu links
[[menu.main]]
    name = "Projects"
    weight = 1
    url  = "projects"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
